os: linux

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

env:
  - AMP_DEBUG=true

services:
  - postgresql

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - travis/install-raphf.sh
  - travis/install-pq.sh
  - composer update -n --prefer-dist

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - travis_retry ./php-coveralls.phar -v
