sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
  fast_finish: true

services:
  - postgresql

install:
  - git clone https://github.com/m6w6/ext-raphf;
    pushd ext-pq;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=raphf.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - git clone https://github.com/m6w6/ext-pq;
    pushd ext-pq;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=pq.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - composer self-update
  - composer install --no-interaction --prefer-source

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
