sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

services:
  - postgresql

install:
  - git clone https://github.com/m6w6/ext-raphf;
    pushd ext-raphf;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=raphf.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - git clone https://github.com/m6w6/ext-pq;
    pushd ext-pq;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=pq.so" >> "$(php -r 'echo php_ini_loaded_file();')";
  - composer self-update
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
